# Generated by Django 3.2.12 on 2022-05-30 18:03

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('WOMEN', 'women')], default=sqlalchemy.sql.expression.null, max_length=10),
        ),
    ]
