# Generated by Django 3.2.12 on 2022-05-31 13:30

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('MEN', 'men'), ('WOMEN', 'women')], default=sqlalchemy.sql.expression.null, max_length=10),
        ),
    ]
