# Generated by Django 3.2.12 on 2022-06-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20220601_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
    ]
