# Generated by Django 3.2.12 on 2022-06-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_item_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
