# Generated by Django 3.2.12 on 2022-06-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_item_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('MEN', 'men'), ('WOMEN', 'women')], max_length=10),
        ),
    ]
