# Generated by Django 3.2.12 on 2022-06-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
