# Generated by Django 3.2.12 on 2022-06-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review'),
        ),
    ]
