# Generated by Django 3.2.12 on 2022-06-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_review_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
