# Generated by Django 3.2.12 on 2022-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='gender',
            field=models.CharField(choices=[('MEN', 'men'), ('WOMEN', 'women')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
