# Generated by Django 3.2.12 on 2022-06-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategory_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('MEN', 'men'), ('WOMEN', 'women')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
