# Generated by Django 3.2.12 on 2022-06-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_variation'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='item.Variation'),
        ),
    ]
