# Generated by Django 3.2.12 on 2022-06-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
