# Generated by Django 3.2.12 on 2022-06-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_appleid',
            field=models.IntegerField(),
        ),
    ]
