# Generated by Django 3.2.12 on 2022-06-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_discount_discount_appleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_appleid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
