# Generated by Django 3.2.12 on 2022-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_discount_discount_appleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcoupon',
            name='active_till',
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
