# Generated by Django 3.2.12 on 2022-06-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
