# Generated by Django 3.2.12 on 2022-06-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
