# Generated by Django 3.2.12 on 2022-06-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_discountcoupon'),
        ('order', '0008_alter_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.discountcoupon'),
            preserve_default=False,
        ),
    ]
