# Generated by Django 3.2.12 on 2022-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_wish'),
        ('order', '0013_auto_20220615_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, to='item.Variation'),
        ),
    ]
