# Generated by Django 3.2.12 on 2022-06-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed'), ('Completed', 'Completed')], default='New', max_length=10),
        ),
    ]
